### PR TITLE
UI & UX improvements

### PR DESCRIPTION
**Pull request by damms005**
- remove hard-coded limits for descriptions
- Add character counter feature
- Remove character counter limit
- Remove limit for UpdateRequest handler rules

...etc.

### CODE REVIEW

**Comment by nafiesl** [comment]
Wow, such a big PR @damms005. Please give me some time to review this PR. Meanwhile, we see travis and style ci still fails, can you please make that pass before we continue on?

Thanks.

**Comment by damms005** [comment]
> travis and style ci still fails?
Fixed :)

>Wow, such a big PR
You have done a very wonderful job by giving us free-pmo. The least we can do is make it better.
 Much later, I hope to PR some other updates I am still working on.

**Comment by nafiesl** [comment]
Thanks @damms005, good to know that this project is helpful for you.

First of all, I see here you make a PR from you `master` branch, it would be better if you can create PR from different branch, eg `ui-ux-improvements`. Can you do that for me, please?

Thanks @damms005 .

**Comment by damms005** [comment]
@nafiesl [You've got it!](https://github.com/nafiesl/free-pmo/pull/43)

**Comment by nafiesl** [comment]
Thank you @damms005, i will take a look tomorrow, since it late night in my time right now.

**Comment by nafiesl** [comment]
I am closing this, and reviewing new PR.

**Pull request closed without merging**
